### ISSUE TITLE
Insert parameter 'hasError' when call onSubmit function

### ISSUE THREAD

**Issue by allangrds** [derekstavis/react-vanilla-form#16]
Actually, in `handleSubmit`, the props function `onSubmit` only receive the data state. It will be easy validate the form with a new param named `hasError`, who will have a boolean containing if has any validation error.

`this.props.onSubmit(this.state.data)`

**Comment by derekstavis** [comment]
Fixed in 7c3e85f5e15122bc8d96c8dd2a91e3421ade896a
