### ISSUE TITLE
Validation property error as false in state when all validations passed

### ISSUE THREAD

**Issue by rsmelo** [derekstavis/react-vanilla-form#22]
the `state.error.<property>` was set as `false` when all property validations passed

eg: there is a Component  `Dropdown` inside the form, when all validations passed the `Form` component put the error prop as `false`and pass it down `Dropdown` component

```
Warning: Failed prop type: Invalid prop `error` of type `boolean` supplied to `Dropdown`, expected `string`.
    in Dropdown
```

**Comment by derekstavis** [comment]
Is this still happening after version 0.5.1? I could work on this issue if it's still an issue!
